version: '3.8'

services:
  dish-insight-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SPEECH_KEY=${SPEECH_KEY}
      - SPEECH_KEY_BACKUP=${SPEECH_KEY_BACKUP}
      - ENDPOINT_URL=${ENDPOINT_URL}
    volumes:
      - ./temp_audio:/app/temp_audio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
